#ifndef QSHERPAONNX_GLOBAL_H
#define QSHERPAONNX_GLOBAL_H
#include <QtCore/qglobal.h>

#if defined(QT_SHERPAONNX_LIBRARY)
#define QT_SHERPAONNX_EXPORT Q_DECL_EXPORT
#else
#define QT_SHERPAONNX_EXPORT Q_DECL_IMPORT
#endif
#endif // QSHERPAONNX_GLOBAL_H

